formspree_form_id: formspree_form_id
name: SufyFlix
title: Sufiyan's TechTome Chronicles
description: Jekflix is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: secondspace8810@gmail.com
disqus_username: sufypunk
